name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        yarn
        yarn build
    - name: Terraform
      run: |
        terraform init -backend-config="token=$TF_TOKEN" infra
        terraform apply -auto-approve infra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_WORKSPACE: uat
        TF_TOKEN: ${{ secrets.TF_TOKEN }}